config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :places, only: [:index, :show]
  resources :entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :place, foreign_key: 'placeId', class_name: 'Place'

  validates :pdfUrl, presence: true
  validates :placeId, presence: true
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :entries, foreign_key: 'placeId'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home
    @entries = if params[:search]
                 Entry.where('title LIKE ? OR author LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
                      .page(params[:page]).per(10)
               else
                 Entry.all.page(params[:page]).per(10)
               end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  def index
    @entries = if params[:search]
                 Entry.where('title LIKE ? OR author LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
                      .page(params[:page]).per(10)
                else
                  Entry.all.page(params[:page]).per(10)
                end              
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to @entry, notice: 'Entry was successfully created.'
    else
      render :new
    end
  end

  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: 'Entry was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @entry.destroy
    redirect_to entries_url, notice: 'Entry was successfully destroyed.'
  end

  private

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:pdfUrl, :ref, :author, :recipient, :title, :placeId, :placeName, :date1, :date2, :date3, :document, :description)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = if params[:search]
                Place.where('name LIKE ?', "%#{params[:search]}%")
              else
                Place.all
              end
  end

  def show
    @place = Place.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<h1>Projeto Iguaçu</h1>

<%= render 'entries/index' %>

app/views/entries/_form.html.erb
<%# filepath: /Users/heliomiguel/code/parana/iguaçu/app/views/entries/_form.html.erb %>
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
      <ul>
        <% entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pdfUrl %>
    <%= form.text_field :pdfUrl %>
  </div>

  <div class="field">
    <%= form.label :ref %>
    <%= form.text_field :ref %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :recipient %>
    <%= form.text_field :recipient %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :placeId %>
    <%= form.text_field :placeId %>
  </div>

  <div class="field">
    <%= form.label :placeName %>
    <%= form.text_field :placeName %>
  </div>

  <div class="field">
    <%= form.label :date1 %>
    <%= form.date_select :date1 %>
  </div>

  <div class="field">
    <%= form.label :date2 %>
    <%= form.date_select :date2 %>
  </div>

  <div class="field">
    <%= form.label :date3 %>
    <%= form.date_select :date3 %>
  </div>

  <div class="field">
    <%= form.label :document %>
    <%= form.text_field :document %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/_index.html.erb
<h1>Entries</h1>
<%= link_to 'New Entry', new_entry_path %>
<%= form_with url: entries_path, method: :get, local: true do %>
  <%= label_tag :search, "Search:" %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Place</th>
      <th>Title</th>
      <th>Author</th>
      <th>Actions</th>
      <!-- Add other headers here -->
    </tr>
  </thead>
  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= link_to entry.date1, entry_path(entry) %></td>
        <td><%= entry.placeName %></td>
        <td><%= entry.title %></td>
        <td><%= entry.author %></td>
        <td>
          <%= link_to 'Show', entry %>
          <%= link_to 'Edit', edit_entry_path(entry) %>
          <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        <!-- Add other entry details here -->
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @entries %>

app/views/entries/edit.html.erb
<%# filepath: /Users/heliomiguel/code/parana/iguaçu/app/views/entries/edit.html.erb %>
<h1>Edit Entry</h1>
<%= render 'form', entry: @entry %>
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Entries</h1>
<%= form_with url: entries_path, method: :get, local: true do %>
  <%= label_tag :search, "Search:" %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Place</th>
      <th>Title</th>
      <th>Author</th>
      <!-- Add other headers here -->
    </tr>
  </thead>
  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= link_to entry.date1, entry_path(entry) %></td>
        <td><%= entry.placeName %></td>
        <td><%= entry.title %></td>
        <td><%= entry.author %></td>
        <!-- Add other entry details here -->
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @entries %>
</ul>

app/views/entries/new.html.erb
<%# filepath: /Users/heliomiguel/code/parana/iguaçu/app/views/entries/new.html.erb %>
<h1>New Entry</h1>
<%= render 'form', entry: @entry %>
<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p><%= @entry.date1 %></p>
<p><%= @entry.author %></p>
<p><%= @entry.recipient %></p>
<h1><%= @entry.title %></h1>
<p><%= @entry.placeName %></p>
<p><%= @entry.description %></p>

app/views/entries/temp.html.erb
<%= render 'entries/index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iguaçu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places</h1>
<%= form_with url: places_path, method: :get, local: true do %>
  <%= label_tag :search, "Search:" %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<ul>
  <% @places.each do |place| %>
    <li>
      <%= link_to place.name, place_path(place) %>
      - <%= place.latitude %>, <%= place.longitude %>
    </li>
  <% end %>
</ul>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>
<p>Latitude: <%= @place.latitude %></p>
<p>Longitude: <%= @place.longitude %></p>